### ISSUE TITLE
An error with the Debian_pkg.sh 

### ISSUE THREAD

**Issue by doodayev** [contextswap/3Days#13]
![image](https://user-images.githubusercontent.com/61427449/236611106-40a168a2-54a4-4e98-9c57-688ca7b9c167.png)
The issue is probably trivial but I thought you'd like to know.
This is on Kubuntu.

**Comment by contextswap** [comment]
Do you have tcsh installed? @nrootconauto wrote all the shell scripts on this repo and there doesn't seem to be an error in the source itself.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/132130142/236611342-16fb953d-dd9d-463a-9b83-32d014838c7a.png">

**Comment by contextswap** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/132130142/236611698-5c787506-9857-4320-a79f-a0838d68d2c1.png">
Cannot duplicate issue when invoked with `tcsh Debian_pkg.sh`. I will assume that you didn't install tcsh.
