### ISSUE TITLE
What happened to the old account?

### ISSUE THREAD

**Issue by divine-architect** [contextswap/3Days#14]

**Comment by divine-architect** [comment]
I meant, why was the ownership given to this account/person?

**Comment by contextswap** [comment]
Both parties have consented.
Here are my current plans:
1. I am currently adding libuv bindings and deprecating dyad bindings as dyad is notoriously slow, I am also adding OpenSSL bindings for cryptography
2. 3Days is not a finished project. It will go through a major revamp very soon when Aiwnios is ported to x86. It will have much more optimization headroom and SSE support for floats
3. I will rewrite parts of this project in as it is fundamentally broken(e.g. stdin in Win32)

**Comment by nrootconauto** [comment]
I transferred ownership as contextswap has been taking good care of my compiler and I'm also working on a new holyC compiler so I'll focus on that for now

**Comment by contextswap** [comment]
My apologies for correcting others' behavior but "issues" like this have zero technicality and thus are not to be subject to GitHub issues. It clogs up the list of organized issues and does not look good. Please send e-mails for a more or less private matter such as repository ownership transfers.
